Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/08/2022
Var
   n, i : inteiro

Inicio
   escreva("Deseja a tabuada para qual valor? ")
   leia(n)
   
   para i de 1 ate 10 faca
      escreval(n, " x ", i, " = ", n * i)
   fimpara

Fimalgoritmo